name: Deploy to GitHub Pages from gh-deployment-workflow branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-github-actions
          path: ${{ github.workspace }}/projects/beginner/gh-deployment-workflow/hello-github-actions

      - name: Checkout gh-deployment-workflow
        uses: actions/checkout@v4
        with:
          ref: gh-deployment-workflow

      - name: Clear site files and re-create directory
        run: |
          DIR="hello-github-actions"
          git rm -rf $DIR
          mkdir -p "$DIR"

      - name: Add CNAME file
        run: |
          FILENAME="CNAME"
          if [ ! -d "$FILENAME" ]; then
            echo "gh.testsraidantimosquitos.win" > "$FILENAME"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-github-actions
          path: hello-github-actions

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push origin gh-deployment-workflow

